# Generated by Django 2.0.2 on 2018-03-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180307_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesblog',
            name='is_delete',
            field=models.BooleanField(verbose_name='文章是否删除'),
        ),
        migrations.AlterField(
            model_name='articlesblog',
            name='is_publish',
            field=models.BooleanField(verbose_name='文章是否发布'),
        ),
    ]
