# Generated by Django 2.0.2 on 2018-03-07 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20180307_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavourTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favour', models.BooleanField(verbose_name='是否点赞')),
            ],
            options={
                'verbose_name': '点赞记录表',
                'verbose_name_plural': '点赞记录表',
            },
        ),
        migrations.AddField(
            model_name='articlesblog',
            name='comments',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='articlesblog',
            name='favours',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='favourtable',
            name='favour_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ArticlesBlog', verbose_name='点赞文章'),
        ),
        migrations.AddField(
            model_name='favourtable',
            name='favour_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='点赞用户'),
        ),
    ]
